# Generated by Django 3.0.7 on 2023-10-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp581', max_length=70),
        ),
    ]
