# Generated by Django 2.2.13 on 2023-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20231013_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp254', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('Hindi', 'HINDI'), ('hausa', 'HAUSA'), ('french', 'FRENCH')], default='english', max_length=10),
        ),
    ]
